name: docker-hub
on:  [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-test:latest
            file: ./Dockerfile

    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to ec2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }} 
            username: ubuntu
            key: ${{ secrets.PRIVATE_KEY }}
            envs: GITHUB_SHA
            script: |
              sudo docker ps
              sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/docker-test
              sudo docker run -d -p 8082:8082 ${{ secrets.DOCKER_HUB_USERNAME }}/docker-test
              sudo docker image prune -f